### ISSUE TITLE
change default database name?

### ISSUE THREAD

**Issue by chrisckchang** [carbon-io/example__contact-service#14]
https://github.com/carbon-io/example__contact-service/blob/master/lib/ContactService.js#L52

default database name is "contacts". our endpoints use collections called "contacts" and "users". should we change the database name, perhaps to "development"?

**Comment by willshulman** [comment]
I don't think so. It makes sense to me that the name of the db is 'contacts' since it is for the contacts app even though there is also a collection call 'contacts'
