### ISSUE TITLE
"_id" field should not be type string

### ISSUE THREAD

**Issue by chrisckchang** [carbon-io/example__contact-service#15]
https://github.com/carbon-io/example__contact-service/blob/master/lib/ContactsEndpoint.js#L50

either "object" or "ObjectId" (supported by EJSON)

thoughts?

**Comment by chrisckchang** [comment]
when you fetch from MongoDB, it'll look something like:

```
[{
    "_id": {
        "$oid": "596559fe3760f200cee5adc6"
    }
    ....
},...]
```

**Comment by willshulman** [comment]
I made it a string intentionally. Why do you not want it as a String?

**Comment by chrisckchang** [comment]
was working on another project and thought it might be useful. https://github.com/carbon-io/example__contact-service/blob/master/lib/ContactsEndpoint.js#L94-L100 was what i was looking for
