### ISSUE TITLE
GET /users/:user/contacts/:_id broken

### ISSUE THREAD

**Issue by chrisckchang** [carbon-io/example__contact-service#2]
Reproduce:

```
% curl -v -H "Content-Type: application/json" -d '{"email": "test@mlab.com", "password":"foo"}' http://localhost:9900/users
% curl -v -H "Content-Type: application/json" -d '{"firstName":"Kevin"}' --user test@mlab.com:foo http://localhost:9900/users/:user/contacts/
% curl --user test@mlab.com:foo http://localhost:9900/users/:user/contacts/:contact
```

Error:
{
"code":500,
"description":"Internal Server Error",
"message":"Output did not validate against schema: 
**{
\"_id\":\"58e2db3f0e26da27d6ad0c29\",
\"firstName\":\"Kevin\",
\"lastName\":{\"$undefined\":true},
\"email\":{\"$undefined\":true},
\"phoneNumbers\":{\"$undefined\":true}
}** 
Schema: {\"type\":\"object\",\"properties\":{\"_id\":{\"type\":\"string\"},\"firstName\":{\"type\":\"string\"},\"lastName\":{\"type\":\"string\"},\"email\":{\"type\":\"string\",\"format\":\"email\"},\"phoneNumbers\":{\"type\":\"object\",\"properties\":{\"home\":{\"type\":\"string\"},\"work\":{\"type\":\"string\"},\"mobile\":{\"type\":\"string\"}}}},\"required\":[\"_id\",\"firstName\"],\"additionalProperties\":false}"}

Required not being honored...? https://github.com/carbon-io/example__contacts-api/blob/c2bda1a42a8a822e8ae351555ff1cb9068e0d8d6/api-docs/users/:user/contacts/:_id.md#responses

Based on error message, looks like it's checking schema against "_publicView": https://github.com/carbon-io/example__contacts-api/blob/c2bda1a42a8a822e8ae351555ff1cb9068e0d8d6/lib/ContactsEndpoint.js#L217-L225.

Also wondering if we can work on formatting for error message.

**Comment by willshulman** [comment]
Can you try again?

**Comment by chrisckchang** [comment]
cloned new project, now getting this error (different order of fields in expected schema):

{
  "code":500,
  "description":"Internal Server Error",
  "message":"Output did not validate against schema: 
  **{
    \"_id\":\"58e2db3f0e26da27d6ad0c29\",
    \"email\":{\"$undefined\":true},
    \"phoneNumbers\":{},
    \"firstName\":\"Kevin\"
  }** 
Schema: {\"type\":\"object\",\"properties\":{\"_id\":{\"type\":\"string\"},\"firstName\":{\"type\":\"string\"},\"lastName\":{\"type\":\"string\"},\"email\":{\"type\":\"string\",\"format\":\"email\"},\"phoneNumbers\":{\"type\":\"object\",\"properties\":{\"home\":{\"type\":\"string\"},\"work\":{\"type\":\"string\"},\"mobile\":{\"type\":\"string\"}}}},\"required\":[\"_id\",\"firstName\"],\"additionalProperties\":false}"}

**Comment by chrisckchang** [comment]
i updated the error message above and in the first comment to make it easier to read. expected schema format is following how it's listed in _publicView: https://github.com/carbon-io/example__contacts-api/blob/master/lib/ContactsEndpoint.js#L217-L233

**Comment by chrisckchang** [comment]
working now 👍🏻
