### ISSUE TITLE
duplicate user email intentionally allowed?

### ISSUE THREAD

**Issue by chrisckchang** [carbon-io/example__contact-service#3]
% curl -v -H "Content-Type: application/json" -d '{"email": "test@mlab.com", "password":"foo"}' http://localhost:9900/users

% curl -v -H "Content-Type: application/json" -d '{"email": "test@mlab.com", "password":"foo"}' http://localhost:9900/users

second command succeeds

**Comment by willshulman** [comment]
No... was going to have an index, although may now add a check as well. Thanks.

**Comment by willshulman** [comment]
Added explicit check in code and also commented in production you would want unique index. Added unique index in setup for unit test.
