### ISSUE TITLE
consider providing a couple quick CURL commands to test proper app deploy

### ISSUE THREAD

**Issue by chrisckchang** [carbon-io/example__contact-service#5]
for example:

curl -v https://radiant-tor-79648.herokuapp.com/users -H "Content-Type: application/json" -d '{"email":"foo@carbon.io", "password":"foobar"}'

curl https://radiant-tor-79648.herokuapp.com/users/59012f3f5e5a210011d05b76 -u 'foo@carbon.io'

**Comment by willshulman** [comment]
Added
