### ISSUE TITLE
Bug in post to /users endpoint

### ISSUE THREAD

**Issue by danieln-ml** [carbon-io/example__contact-service#6]
response.headers.location contains an extra slash in it.

{
  "date": "Fri, 12 May 2017 22:41:42 GMT",
  "x-powered-by": "Express",
  "etag": "W/\"0-0\"",
  **"location": "/users//59163a26a48c0d2a43474f22",**
  "carbonio-id": "\"59163a26a48c0d2a43474f22\"",
  "access-control-allow-origin": "*",
  "connection": "close",
  "content-length": "0"
}

**Comment by chrisckchang** [comment]
are both "location" + "carbonio-id" supposed to be there? looks different than documented: https://github.com/carbon-io/example__contacts-api/blob/master/api-docs/users.md#responses

**Comment by willshulman** [comment]
Both headers are listed in the docs (albeit with a \n which should be fixed). Will look into double slashes

**Comment by willshulman** [comment]
Greg you seeing double slashes like reported above?

**Comment by gregbanks** [comment]
looks like this project was depending on an out of date version of carbon-io (0.5.x instead of 0.6.x). that being said, the latest version of the 0.5.x branch should have handled the extra slash (https://github.com/carbon-io/carbond/blob/v0.5.4/lib/collections/Collection.js#L347).

**Comment by gregbanks** [comment]
... forgot to mention, the location header generated for PUTs had the potential to include the extra slash in the location header. this has been fixed in the 0.6.x branch.
